# Generated by Django 3.2.4 on 2021-06-03 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enjoyed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='minutes_spend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
